In [1]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, classification_report, confusion_matrix

In [2]:
data = pd.read_pickle("../../../data/03_training_set/training_set.pkl")

bins = (-np.inf, 0, 15, 35, 75, 200, np.inf)
group_names = ['0.brak', '1.bardzo mało', '2.mało', '3.średnio', '4.dużo', '5.bardzo dużo']
data['new_watchers'] = pd.cut(data['new_watchers'], bins=bins, labels=group_names)

labels = LabelEncoder()
data['new_watchers'] = labels.fit_transform(data['new_watchers'])

X = data.drop(['new_watchers'], axis=1)
y = data['new_watchers']

s = StandardScaler()
X = s.fit_transform(X)

X_train, X_test, y_train, y_test = \
    train_test_split(X, y, test_size=0.20, random_state=42)

# Las losowy

W przypadku lasu losowego testowałem wiele wariantów, jednak nie ma znaczących różnic w wynikach, zatem zdecydowałem się zostawić tylko domyślny zestaw parametrów.

In [3]:
from sklearn.ensemble import RandomForestClassifier

In [4]:
def random_forest_summary(X_train, X_test, y_train, y_test, 
                          n_jobs=4, max_depth=None, n_estimators=100):
    random_forest = RandomForestClassifier(n_jobs=n_jobs, verbose=1, n_estimators=n_estimators, max_depth=max_depth)
    random_forest.fit(X_train, y_train)
    
    # podsumowanie wynikow
    y_pred_default = random_forest.predict(X_test).astype(int)
    print(f'mean_squared_error: {mean_squared_error(y_test, y_pred_default)}')
    print(f'train score: {random_forest.score(X_train, y_train)}')
    print(f'test score: {random_forest.score(X_test, y_test)}')
    print(classification_report(y_test, y_pred_default))
    print(confusion_matrix(y_test, y_pred_default))

In [5]:
random_forest_summary(X_train, X_test, y_train, y_test)

[Parallel(n_jobs=4)]: Using backend ThreadingBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done  42 tasks      | elapsed:   40.0s
[Parallel(n_jobs=4)]: Done 100 out of 100 | elapsed:  2.2min finished
[Parallel(n_jobs=4)]: Using backend ThreadingBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done  42 tasks      | elapsed:    1.1s
[Parallel(n_jobs=4)]: Done 100 out of 100 | elapsed:    2.7s finished


mean_squared_error: 0.0013393313284786024


[Parallel(n_jobs=4)]: Using backend ThreadingBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done  42 tasks      | elapsed:    4.7s
[Parallel(n_jobs=4)]: Done 100 out of 100 | elapsed:   11.1s finished


train score: 0.9999827405280017


[Parallel(n_jobs=4)]: Using backend ThreadingBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done  42 tasks      | elapsed:    1.2s
[Parallel(n_jobs=4)]: Done 100 out of 100 | elapsed:    2.8s finished


test score: 0.9996133888948722
              precision    recall  f1-score   support

           0       1.00      1.00      1.00    361543
           1       0.80      0.82      0.81       133
           2       0.70      0.69      0.70       125
           3       0.78      0.80      0.79       162
           4       0.87      0.83      0.85       129
           5       0.86      0.41      0.56        29

    accuracy                           1.00    362121
   macro avg       0.84      0.76      0.78    362121
weighted avg       1.00      1.00      1.00    362121

[[361537      6      0      0      0      0]
 [     8    109     15      1      0      0]
 [     0     19     86     18      2      0]
 [     0      2     20    130     10      0]
 [     1      0      1     18    107      2]
 [    13      0      0      0      4     12]]
